#! /bin/dash
if [ "$#" -gt 0 ] ; then
	echo "Usage: fcheat ..." >&2
	return -1
fi

# function enables to choose a cheatsheet to view
eval `cheat -l | tail -n +2 | fzf | awk -v vars="$*" '{ print "cheat " $1 " -t " $3, vars }'`
