#! /bin/sh

#### AUTOSTART ####
killall -9 sxhkd dunst picom 

export mNETWORK="$(ip link | awk '/state UP/ {print $2}' | sed 's/:$//' )"

sxhkd -m 1 &
#sxhkd -c ./config/sxhkd/sxhkdrc &
nitrogen --restore &
#setxkbmap -layout "us,ru" -option "grp:shifts_toggle,grp_led:scroll" &
setxkbmap -layout "us,ru" -option "grp:ctrls_toggle,grp_led:scroll,caps:escape" &

### MONITORS ####
# from : https://github.com/aca/dotfiles/blob/master/.config/bspwm/bspwmrc
if [ "$(bspc query -M --names | wc -l)" = 3 ]; then
  bspc monitor $(xrandr -q | grep '^eDP.*\bconnected' | awk '{print $1}') -d 1 2 3
  bspc monitor $(xrandr -q | grep '^DP.*\bconnected' | awk '{print $1}' | awk 'NR==1') -d 4 5 6
  bspc monitor $(xrandr -q | grep '^DP.*\bconnected' | awk '{print $1}' | awk 'NR==2') -d 7 8 9
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9
fi
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

./.config/polybar/launch.sh &

./.config/bspwm/autorun.sh &

#### BSPWM configuration ####
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer off
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-I-1)

## applications

### WINDOW RULES ###{{{
#-----------Class-Name--------------------Workspaces---Focus----Follow------Other Settings-----------------------------#
bspc rule -r *
bspc rule -a Zathura                                  focus=on follow=on state=tiled
bspc rule -a Connman-gtk                              focus=on follow=on state=floating
bspc rule -a Pavucontrol                              focus=on follow=on state=floating
bspc rule -a Pcmanfm                                  focus=on follow=on state=floating
bspc rule -a SimpleScreenRecorder                     focus=on follow=on state=floating
bspc rule -a Sxiv                                     focus=on follow=on state=floating
bspc rule -a Lxappearance                             focus=on follow=on state=floating
bspc rule -a java-lang-Thread                                            state=floating
bspc rule -a Screenkey                     manage=off
bspc rule -a pop-up                        state=floating
#---------------------------------------------------------------------------------------------------------------------------#}}}

bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a "Xfce4-appfinder" state=floating sticky=on
bspc rule -a "xfce4-appfinder" state=floating center=true
bspc rule -a "Application Finder" state=floating sticky=on
bspc rule -a file-roller state=floating center=true
bspc rule -a gcolor2 state=floating center=true
bspc rule -a "Pale moon" desktop='^2' follow=on
bspc rule -a "Mail" desktop='^8' follow=on
bspc rule -a Firefox private=pc

bspc rule -a XTerm:dropXterm state=floating
bspc rule -a Xterm state=floating center=true

bspc rule -a vlc state=floating sticky=on
bspc rule -a 'vlc' desktop="^5" border=off follow=on
bspc rule -a 'Opera' desktop="^4" follow=on


ps x | grep bspswallow | grep -v grep) || bspswallow &
