#! /bin/sh

#### AUTOSTART ####
#export WIRELESS=wlan0
#export mNETWORK=eth1
export mNETWORK="$(ip link | awk '/state UP/ {print $2}' | sed 's/:$//' )"

sxhkd -m 1 &
#sxhkd -c ./config/sxhkd/sxhkdrc &
nitrogen --restore &
# setxkbmap -layout "us,ru" -option "grp:lalt_lshift_toggle,grp_led:scroll" &
#setxkbmap -layout "us,ru" -option "grp:shifts_toggle,grp_led:scroll" &
setxkbmap -layout "us,ru" -option "grp:ctrls_toggle,grp_led:scroll",caps:escape &

### MONITORS ####
# from : https://github.com/aca/dotfiles/blob/master/.config/bspwm/bspwmrc
if [ "$(bspc query -M --names | wc -l)" = 3 ]; then
  bspc monitor $(xrandr -q | grep '^eDP.*\bconnected' | awk '{print $1}') -d 1 2 3
  bspc monitor $(xrandr -q | grep '^DP.*\bconnected' | awk '{print $1}' | awk 'NR==1') -d 4 5 6
  bspc monitor $(xrandr -q | grep '^DP.*\bconnected' | awk '{print $1}' | awk 'NR==2') -d 7 8 9 
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9
fi
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


#bspc monitor DisplayPort-0 -d 1 2 3
#bspc monitor DisplayPort-1 -d 4 5 6
#bspc monitor HDMI-A-0 -d 7 8 9
#bspc monitor DVI-I-1 -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor -d 1 2 3 4 5 6 7 8 9

./.config/polybar/launch.sh &

nm-applet &

#xsettinsd &

if [ -f /usr/lib/po*kit*-gnome/polkit-gnome-authentication-agent-1 ] ; then
    /usr/lib/po*kit*-gnome/polkit-gnome-authentication-agent-1 &
fi

if hash pcmanfm > /dev/null 2>&1 ; then
    dbus-launch pcmanfm -d &
fi
if hash udiskie > /dev/null 2>&1 ; then
    udiskie &
fi
if hash tilda > /dev/null 2>&1 ; then
    tilda &
fi
if hash picom > /dev/null 2>&1 ; then
        picom --experimental-backends --fading --config "$HOME/.config/picom/picom.conf" &
	    until pidof compton > /dev/null; do 
		    sleep 0.1s
        done
elif hash compton > /dev/null 2>&1 ; then
	    compton --config "$HOME/.dotfiles/config/compton/compton.conf" &
	    until pidof compton > /dev/null; do 
		    sleep 0.1s
	    done
fi

#xfce4-power-manager &

# prevent monitor to sleep when view movies
xset -dpms; xset s off &

#### BSPWM configuration ####
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       on
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_by_distance    true
bspc config focus_follows_pointer on
# bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#### BSPWM coloring ####
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

#bspc config focused_border_color    "#00FFFF"
#bspc config active_border_color     "#FF00FF"
#bspc config normal_border_color     "#800000"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-I-1)

## applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a "Xfce4-appfinder" state=floating sticky=on
bspc rule -a "Application Finder" state=floating sticky=on
bspc rule -a vlc state=floating sticky=on
bspc rule -a file-roller state=floating center=true
bspc rule -a lxappearance state=floating center=true
bspc rule -a gcolor2 state=floating center=true
bspc rule -a "xfce4-appfinder" state=floating center=true
bspc rule -a "pcmanfm" state=floating center=true
bspc rule -a "Pcmanfm" state=floating center=true
bspc rule -a "Pale moon" desktop='^2' follow=on
bspc rule -a "Mail" desktop='^8' follow=on
#bspc rule -a "qutebrowser" desktop='^3' follow=on
bspc rule -a Firefox private=pc

bspc rule -a XTerm:dropXterm state=floating
bspc rule -a Xterm state=floating center=true
bspc rule -a dropdown sticky=on state=floating hidden=on

bspc rule -a 'vlc' desktop="^4" border=off follow=on
