#! /bin/sh

#### AUTOSTART ####

sxhkd &
compton &
nitrogen --restore &
conky &
#./.config/bspwm/panel.sh &
./.config/polybar/launch.sh &

#### MONITORS ####

#bspc monitor DisplayPort-0 -d 1 2 3
#bspc monitor DisplayPort-1 -d 4 5 6
#bspc monitor HDMI-A-0 -d 7 8 9
#bspc monitor DVI-I-1 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

#### BSPWM configuration ####
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#### BSPWM coloring ####
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-I-1)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a "Pale moon" desktop='^2' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Subl3 desktop='^3' follow=on
bspc rule -a Atom desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a smplayer desktop='^6' follow=on
bspc rule -a vlc desktop='^6' follow=on
bspc rule -a Transmission-gtk desktop='^7' follow=on
bspc rule -a Thunar desktop='^8' follow=on
bspc rule -a Nemo desktop='^8' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Stacer state=floating

pplications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

