[[snippets]]
  description = "Obtain external IP address"
  command = "curl ifconfig.co"
  output = ""

[[snippets]]
  description = "Ping host with 5 packets."
  command = "ping -c 5 <host=google.com>"
  output = ""

[[snippets]]
  description = "Search a pattern in given dirs with bat"
  command = "batgrep <Pattern=Hi> <Dirs=~/Code/go/src/**>"
  output = ""

[[snippets]]
  description = "git push to the given branch"
  command = "git push origin <branch=master>"
  output = ""

[[snippets]]
  description = "Expand a shortened URL"
  command = "curl --head --location <url=https://bit.ly/2yDyS4T> "
  output = ""

[[snippets]]
  description = "dump iso image to disk-usb if=inputFile of=outputDisk"
  command = "sudo dd bs=4M <InputISO=if-Downloads/My.iso> <OutputDisk=of-/dev/sdX> && sync"
  output = ""

[[snippets]]
  description = "create a log file nvim.log with verbose level 10"
  command = "nvim -V10nvim.log"
  output = ""

[[snippets]]
  description = "find all broken sym links in current directory"
  command = "find . -type l ! -exec test -e {} \\; -print"
  output = ""

[[snippets]]
  description = "determine programmatically which WM is running"
  command = "wmctrl -m | rg Name |  awk -F \": \" '{print $2}'"
  output = ""
