#! /bin/sh

fcolor="$(bspc config focused_border_color)"

  bspc config border_width 8 && \
  bspc config focused_border_color "$(xrdb -q | awk NR==9'{print $2}')" && \
  sleep '0.5' && \
  bspc config border_width 2 && \
  bspc config focused_border_color "$fcolor"
