#!/bin/sh
# Feed this script a link and it will give dmenu
# some choice programs to use to open it.

case "$(printf "copy url\\nmpv\\nmpv (loop)\\nqueue download\\nqueue youtube-dl\\nfeh\\nsxiv\\nbrowser\\nw3m\\nmpv (float) \\nytdll" | dmenu -i -p "Open link with what program?")" in
	"copy url") echo "$1" | xclip -selection clipboard ;;
	mpv) setsid -f mpv -quiet "$1" >/dev/null 2>&1 & ;;
	"queue download") tsp curl -LO "$1" >/dev/null 2>&1 ;;
	"queue youtube-dl") tsp youtube-dl --write-metadata -ic "$1" >/dev/null 2>&1 ;;
	browser) setsid -f "$BROWSER" "$1" >/dev/null 2>&1 & ;;
	feh) setsid -f feh "$1" >/dev/null 2>&1 & ;;
	sxiv) setsid -f sxiv "$1" >/dev/null 2>&1 & ;;
	w3m) w3m "$1" >/dev/null 2>&1 ;;
	ytdll) setsid -f st -e ytdll "$1" >/dev/null 2>&1 & ;;
esac
