#!/bin/bash

## from: https://my-take-on.tech/2020/07/03/some-tricks-for-sxhkd-and-bspwm/

awk '/^[a-zA-Z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc{,.common} |
    column -t -s $'\t' |
    rofi -dmenu -i -columns 1 -markup-rows -no-show-icons -width 1000 -font "Liberation Mono 9.7" -lines 15 -yoffset 40

