#!/usr/bin/sh
LINES=33

vvimview () {
    bat -l VimL "$1"
}


case "$1" in
  *.png|*.jpeg|*.jpg|*.gif) stpv "$1";;
  *.md|*.markdown) glow -s dark "$1";;
  *.zsh*|*.bash*|*.git*|*.sh*) pistol "$1";;
  *.lfrc) bat -l conf "$1";;
  *.vim*) bat -l VimL "$1";;
  *) bat --color always "$1";;
  esac

